spring:
    application:
        name: profile50
    datasource:
        url: jdbc:postgresql://localhost:15001/profile50
        username: tk-apap-50
        password: tk-apap-50
    jpa:
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
server:
    port: 8084